[tool.poetry]
name = "streamlit-app"
version = "0.1.0"
description = ""
authors = ["dash-pablo-garcia <pablo.garcia-borreguero@dashmote.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
adjustText = "^0.7.3"
streamlit = "^1.12.0"
pandas = ">=1.3.0, <1.3.9"
matplotlib = "^3.5.3"
